import { openDatabase, type MaliniDatabase } from './driver';
import {
	MIGRATION_0001_INITIAL,
	MIGRATION_0002_AGENT_SESSIONS,
	MIGRATION_0003_AGENT_EVENTS,
	MIGRATION_0004_CORE_WORKSPACE_SCOPE,
	MIGRATION_0005_AGENT_CHECKPOINTS,
	MIGRATION_0006_PROVIDER_SESSION_ID,
	MIGRATION_0007_AGENT_SESSION_DISPLAY_NAME,
	MIGRATION_0008_AGENT_SESSION_ARCHIVED_AT,
	MIGRATION_0009_REPAIR_LEGACY_TIMESTAMPS,
	MIGRATION_0010_AGENT_ATTACHMENTS,
	MIGRATION_0011_WORKSPACE_PREVIEW_INTENTS,
	MIGRATION_0012_CORE_AGENT_PROVIDER,
	MIGRATION_0013_OWNED_LOOP_ONLY,
	MIGRATION_0014_AGENT_RUN_CHANGES,
	MIGRATION_0015_AGENT_INTERACTIONS,
	MIGRATION_0017_CLOSE_TERMINAL_INTERACTIONS,
	MIGRATION_0018_DOCKER_CONTAINERS,
	MIGRATION_0019_DOCKER_CONTAINER_OWNER_PID,
	MIGRATION_0020_BACKFILL_CORE_WORKSPACE_SCOPE,
	MIGRATION_0021_AGENT_USER_BASELINES,
	MIGRATION_0022_AGENT_RUN_CHECKPOINT_FAILURES,
	MIGRATION_0023_CONNECTED_REPOSITORIES,
	MIGRATION_0024_WORKSPACE_ROUTINES,
	MIGRATION_0025_AGENT_CHECKPOINTS_OBSOLETED_AT,
	MIGRATION_0025_AGENT_CHECKPOINT_OBSOLETED_INDEX,
	MIGRATION_0025_AGENT_RUNS_OBSOLETED_AT,
	MIGRATION_0025_AGENT_RUN_OBSOLETED_INDEX,
	MIGRATION_0026_AGENT_SESSION_FORKED_FROM,
	MIGRATION_0026_AGENT_SESSION_FORK_SEQ,
	MIGRATION_0027_DROP_CHECKS_AND_PREVIEWS,
	MIGRATION_0028_DROP_AGENT_PROVIDER,
	MIGRATION_0029_SMACK_IDENTIFIERS,
	MIGRATION_0030_DROP_WORKSPACE_SCOPE,
} from './migrations';
import { upsertProject } from '$shared/repositories/repositories.platform';
import { upsertWorkstream } from '$shared/repositories/repositories.platform';

export function seedWorkstream(
	db: MaliniDatabase,
	workstreamId: string,
	createdAt = '2026-07-22T00:00:00Z',
): void {
	const projectId = `project-${workstreamId}`;
	upsertProject(db, {
		id: projectId,
		name: projectId,
		repoPath: `/tmp/${projectId}`,
		defaultBranch: 'main',
		createdAt,
	});
	upsertWorkstream(db, {
		id: workstreamId,
		projectId,
		name: workstreamId,
		path: `/tmp/${workstreamId}`,
		branch: `codex/${workstreamId}`,
		baseBranch: 'main',
		status: 'active',
		createdAt,
	});
}

const LADDER: readonly (readonly [version: number, statement: string])[] = [
	[1, MIGRATION_0001_INITIAL],
	[2, MIGRATION_0002_AGENT_SESSIONS],
	[3, MIGRATION_0003_AGENT_EVENTS],
	[4, MIGRATION_0004_CORE_WORKSPACE_SCOPE],
	[5, MIGRATION_0005_AGENT_CHECKPOINTS],
	[6, MIGRATION_0006_PROVIDER_SESSION_ID],
	[7, MIGRATION_0007_AGENT_SESSION_DISPLAY_NAME],
	[8, MIGRATION_0008_AGENT_SESSION_ARCHIVED_AT],
	[9, MIGRATION_0009_REPAIR_LEGACY_TIMESTAMPS],
	[10, MIGRATION_0010_AGENT_ATTACHMENTS],
	[11, MIGRATION_0011_WORKSPACE_PREVIEW_INTENTS],
	[12, MIGRATION_0012_CORE_AGENT_PROVIDER],
	[13, MIGRATION_0013_OWNED_LOOP_ONLY],
	[14, MIGRATION_0014_AGENT_RUN_CHANGES],
	[15, MIGRATION_0015_AGENT_INTERACTIONS],
	[17, MIGRATION_0017_CLOSE_TERMINAL_INTERACTIONS],
	[18, MIGRATION_0018_DOCKER_CONTAINERS],
	[19, MIGRATION_0019_DOCKER_CONTAINER_OWNER_PID],
	[20, MIGRATION_0020_BACKFILL_CORE_WORKSPACE_SCOPE],
	[21, MIGRATION_0021_AGENT_USER_BASELINES],
	[22, MIGRATION_0022_AGENT_RUN_CHECKPOINT_FAILURES],
	[23, MIGRATION_0023_CONNECTED_REPOSITORIES],
	[24, MIGRATION_0024_WORKSPACE_ROUTINES],
	[25, MIGRATION_0025_AGENT_RUNS_OBSOLETED_AT],
	[25, MIGRATION_0025_AGENT_RUN_OBSOLETED_INDEX],
	[25, MIGRATION_0025_AGENT_CHECKPOINTS_OBSOLETED_AT],
	[25, MIGRATION_0025_AGENT_CHECKPOINT_OBSOLETED_INDEX],
	[26, MIGRATION_0026_AGENT_SESSION_FORKED_FROM],
	[26, MIGRATION_0026_AGENT_SESSION_FORK_SEQ],
	[27, MIGRATION_0027_DROP_CHECKS_AND_PREVIEWS],
	[28, MIGRATION_0028_DROP_AGENT_PROVIDER],
	...MIGRATION_0029_SMACK_IDENTIFIERS.map(([, statement]) => [29, statement] as const),
	...MIGRATION_0030_DROP_WORKSPACE_SCOPE.map(([, statement]) => [30, statement] as const),
];

export function ladderDatabase(version: number, stampedVersion = version): MaliniDatabase {
	const db = openDatabase(':memory:');
	for (const [step, statement] of LADDER) {
		if (step <= version) db.exec(statement);
	}
	db.exec(`PRAGMA user_version = ${stampedVersion};`);
	return db;
}
