import { randomBytes } from 'node:crypto';
import type { ContainerOwner } from './records';

export const LABEL_APP = 'app.malini.app';
export const LABEL_WORKSTREAM = 'app.malini.workstream';
export const LABEL_COMPOSE_PROJECT = 'app.malini.compose-project';
export const LABEL_SERVICE = 'app.malini.service';
export const LABEL_OWNER = 'app.malini.owner';

export const LEGACY_LABEL_WORKSPACE = 'app.malini.workspace';
export const LEGACY_OWNER_WORKSPACE = 'workspace';

export const OWNERSHIP_LABEL_KEYS = [
	LABEL_APP,
	LABEL_WORKSTREAM,
	LABEL_COMPOSE_PROJECT,
	LABEL_SERVICE,
	LABEL_OWNER,
] as const;

export const MAX_COMPOSE_PROJECT_NAME_LENGTH = 63;

export const PRODUCTION_BUNDLE_IDENTIFIER = 'app.malini.desktop';
export const DEVELOPMENT_BUNDLE_IDENTIFIER = 'app.malini.desktop.dev';

export function newAppInstanceId(): string {
	try {
		return randomBytes(12).toString('hex');
	} catch {
		return `${process.pid.toString(16)}-${Date.now().toString(16)}`;
	}
}

export const APP_INSTANCE_ID = newAppInstanceId();

export interface OwnershipLabels {
	readonly bundleIdentifier: string;
	readonly appInstanceId: string;
	readonly workstreamId: string;
	readonly composeProject: string;
	readonly service: string;
	readonly owner: ContainerOwner;
}

export function ownershipLabels(input: OwnershipLabels): OwnershipLabels {
	assertSafeLabelValue('bundle identifier', input.bundleIdentifier);
	assertSafeLabelValue('app instance id', input.appInstanceId);
	assertSafeLabelValue('workstream id', input.workstreamId);
	assertSafeComposeProjectName(input.composeProject);
	assertSafeComposeServiceName(input.service);
	return { ...input };
}

export function composeLabels(labels: OwnershipLabels): Array<readonly [string, string]> {
	return [
		[LABEL_APP, labels.bundleIdentifier],
		[LABEL_WORKSTREAM, labels.workstreamId],
		[LABEL_COMPOSE_PROJECT, labels.composeProject],
		[LABEL_SERVICE, labels.service],
		[LABEL_OWNER, labels.owner],
	];
}

export function assertSafeComposeServiceName(value: string): void {
	const valid =
		value.length > 0 &&
		value.length <= 255 &&
		!value.startsWith('-') &&
		/^[A-Za-z0-9._-]+$/.test(value);
	if (valid) return;
	throw new Error(
		`Docker Compose service name must be 1-255 ASCII letters, numbers, dots, underscores, or hyphens and cannot start with a hyphen, not \`${value}\``,
	);
}

export function assertSafeComposeProjectName(value: string): void {
	const valid =
		value.length <= MAX_COMPOSE_PROJECT_NAME_LENGTH && /^[a-z0-9][a-z0-9_-]*$/.test(value);
	if (valid) return;
	throw new Error(
		`Docker Compose project name must be 1-${MAX_COMPOSE_PROJECT_NAME_LENGTH} lowercase letters, digits, dashes, or underscores and must start with a letter or digit, not \`${value}\``,
	);
}

export function assertSafeLabelValue(what: string, value: string): void {
	const valid = value.length > 0 && value.length <= 255 && /^[A-Za-z0-9._\-/:+]+$/.test(value);
	if (valid) return;
	throw new Error(
		`docker ownership ${what} must be 1-255 ASCII letters, numbers, or \`._-/:+\`, not \`${value}\``,
	);
}

export function composeProjectName(repository: string, scope: string): string {
	const readableRepository = normalizeProjectSegment(repository);
	const readableScope = normalizeProjectSegment(scope);
	const direct = `${readableRepository}-${readableScope}`;
	if (direct.length <= MAX_COMPOSE_PROJECT_NAME_LENGTH) return direct;
	const suffix = `${charPrefix(readableScope, 20)}-${shortHash(scope)}`;
	const baseLength = Math.max(1, MAX_COMPOSE_PROJECT_NAME_LENGTH - 1 - suffix.length);
	return `${charPrefix(readableRepository, baseLength)}-${suffix}`;
}

function normalizeProjectSegment(value: string): string {
	const lowered = value.toLowerCase();
	const stripped = lowered.startsWith('@') ? lowered.slice(1) : lowered;
	let collapsed = '';
	let inRun = false;
	for (const character of stripped) {
		const keep = /^[a-z0-9_-]$/.test(character);
		if (keep) {
			collapsed += character;
			inRun = false;
			continue;
		}
		if (!inRun) {
			collapsed += '-';
			inRun = true;
		}
	}
	const trimmed = collapsed.replace(/^[^a-z0-9]+/, '');
	if (trimmed.length === 0) return 'repository';
	return charPrefix(trimmed, MAX_COMPOSE_PROJECT_NAME_LENGTH);
}

function charPrefix(value: string, length: number): string {
	return [...value].slice(0, length).join('');
}

export function shortHash(value: string): string {
	let hash = 2_166_136_261;
	for (const character of value) {
		hash ^= character.codePointAt(0) ?? 0;
		hash = Math.imul(hash, 16_777_619);
	}
	return (hash >>> 0).toString(36).slice(0, 7);
}

export function composeLabelOverlayYaml(labels: OwnershipLabels): string {
	let yaml = '# Generated by malini. Do not edit.\n';
	yaml +=
		'# Identifies the containers malini started so they can be reclaimed on the next launch.\n';
	yaml += 'services:\n';
	yaml += `  ${labels.service}:\n`;
	yaml += '    labels:\n';
	for (const [key, value] of composeLabels(labels)) {
		yaml += `      ${key}: "${value}"\n`;
	}
	return yaml;
}
